### ISSUE TITLE
Tomorrow date determine issue

### ISSUE THREAD

**Issue by liggth** [GeorgII-web/cbr-api-exchange#1]
Currently your code 

`return $lastDateObj === $dateObj;` 

always returns false. Could you check this and disable strict comparison?

**Comment by GeorgII-web** [comment]
@liggth thank you for a comment.

Have checked and improved the code by a default Carbon comparison method:
```
return $lastDateObj->eq($dateObj);
```

New release is there, pls check
https://github.com/GeorgII-web/cbr-api-exchange/releases/tag/1.0.3
